In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style('whitegrid')
%matplotlib inline

In [3]:
import os
path = os.getcwd() + '/Data/pydata.csv'
df = pd.read_csv(path)

In [4]:
df.head()

CLAIM_NUM NEXT_SERVICE MEMBER_SEX  AGE_GROUP  CODE_1  CODE_2  CODE_3  \
0   23005370         OTPT          M  PreSchool   654.0     NaN     NaN   
1   23257313         OTPT          M  PreSchool   254.0   654.0     NaN   
2   23027711         OTPT          M  PreSchool   136.0     NaN     NaN   
3   23305598         OTPT          M  PreSchool   136.0     NaN     NaN   
4   23112424         OTPT          M  PreSchool   136.0     NaN     NaN   

   CODE_4  CODE_5  CODE_6  CODE_7  Asthma  COPD  Diabetes  HeartFailure  \
0     NaN     NaN     NaN     NaN     NaN   NaN       NaN           NaN   
1     NaN     NaN     NaN     NaN     NaN   NaN       NaN           NaN   
2     NaN     NaN     NaN     NaN     NaN   NaN       NaN           NaN   
3     NaN     NaN     NaN     NaN     NaN   NaN       NaN           NaN   
4     NaN     NaN     NaN     NaN     NaN   NaN       NaN           NaN   

   Hypertension  Psychoses  MoodDisorder  
0           NaN        NaN           NaN  
1           NaN        NaN           NaN  
2           NaN        NaN           NaN  
3           NaN        NaN           NaN  
4           NaN        NaN           NaN

In [5]:
df.NEXT_SERVICE.value_counts()

OTPT    12142549
ED        925539
INPT      138024
Name: NEXT_SERVICE, dtype: int64

In [6]:
y = df.NEXT_SERVICE

In [7]:
X = df.iloc[:,2:]
X.columns

Index(['MEMBER_SEX', 'AGE_GROUP', 'CODE_1', 'CODE_2', 'CODE_3', 'CODE_4',
       'CODE_5', 'CODE_6', 'CODE_7', 'Asthma', 'COPD', 'Diabetes',
       'HeartFailure', 'Hypertension', 'Psychoses', 'MoodDisorder'],
      dtype='object')

**Binarize y**

In [8]:
y[y=='OTPT'] = 'NOT_ED'
y[y=='INPT'] = 'NOT_ED'

C:\Users\User\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
C:\Users\User\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  


In [9]:
from sklearn import preprocessing
le = preprocessing.LabelBinarizer()

In [10]:
y = le.fit_transform(y)
y

array([[1],
       [1],
       [1],
       ...,
       [1],
       [1],
       [1]])

**Change NAs in X**

In [11]:
X = X.fillna(0)

**Tidy Up/Factorize X**

In [12]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13206112 entries, 0 to 13206111
Data columns (total 16 columns):
MEMBER_SEX      object
AGE_GROUP       object
CODE_1          float64
CODE_2          float64
CODE_3          float64
CODE_4          float64
CODE_5          float64
CODE_6          float64
CODE_7          float64
Asthma          float64
COPD            float64
Diabetes        float64
HeartFailure    float64
Hypertension    float64
Psychoses       float64
MoodDisorder    float64
dtypes: float64(14), object(2)
memory usage: 1.6+ GB


In [13]:
X = X.astype('category')

In [14]:
del df
#X.pop('CODE_6');
#X.pop('CODE_7');

In [15]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13206112 entries, 0 to 13206111
Data columns (total 16 columns):
MEMBER_SEX      category
AGE_GROUP       category
CODE_1          category
CODE_2          category
CODE_3          category
CODE_4          category
CODE_5          category
CODE_6          category
CODE_7          category
Asthma          category
COPD            category
Diabetes        category
HeartFailure    category
Hypertension    category
Psychoses       category
MoodDisorder    category
dtypes: category(16)
memory usage: 289.8 MB


In [16]:
X.AGE_GROUP.unique(), X.MEMBER_SEX.unique()

([PreSchool, Child, Baby, Young Adult, Teen, Middle Age, Adult, Senior, Very Senior]
 Categories (9, object): [PreSchool, Child, Baby, Young Adult, ..., Middle Age, Adult, Senior, Very Senior],
 [M, F]
 Categories (2, object): [M, F])

In [17]:
from sklearn.preprocessing import LabelEncoder
le = preprocessing.LabelEncoder()
le.fit(['PreSchool', 'Child', 'Baby', 'Young Adult', 'Teen', 'Middle Age', 'Adult', 'Senior', 'Very Senior'])
X.AGE_GROUP = le.transform(X.AGE_GROUP)

In [18]:
le.fit(['M', 'F'])
X.MEMBER_SEX = le.transform(X.MEMBER_SEX)

In [19]:
X.AGE_GROUP.head(10), X.MEMBER_SEX.head(10)

(0    4
 1    4
 2    4
 3    4
 4    4
 5    4
 6    4
 7    4
 8    4
 9    4
 Name: AGE_GROUP, dtype: int64, 0    1
 1    1
 2    1
 3    1
 4    1
 5    1
 6    1
 7    1
 8    1
 9    1
 Name: MEMBER_SEX, dtype: int64)

In [20]:
#ind_AGE_GROUP = pd.get_dummies(X['AGE_GROUP'], prefix='AGE_GROUP')
#ind_CODE_1 = pd.get_dummies(X['CODE_1'], prefix='CODE_1')
#ind_CODE_2 = pd.get_dummies(X['CODE_2'], prefix='CODE_2')
#ind_CODE_3 = pd.get_dummies(X['CODE_3'], prefix='CODE_3')
#ind_CODE_4 = pd.get_dummies(X['CODE_4'], prefix='CODE_4')
#ind_CODE_5 = pd.get_dummies(X['CODE_5'], prefix='CODE_5')

In [21]:
#X = pd.concat([X.MEMBER_SEX, ind_AGE_GROUP, ind_CODE_1, ind_CODE_2, ind_CODE_3, ind_CODE_4, ind_CODE_5,
#               X.Asthma, X.COPD, X.Diabetes, X.HeartFailure, X.Hypertension, X.Psychoses, X.MoodDisorder], axis=1)

## Train Test Split

In [22]:
from sklearn.model_selection import train_test_split

In [23]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.2)

## Ensemble Models

### Random Forest

**Base Model**

In [24]:
from sklearn.ensemble import RandomForestClassifier

In [25]:
np.unique(y, return_counts=True)

(array([0, 1]), array([  925539, 12280573], dtype=int64))

In [26]:
counts = np.unique(y, return_counts=True)[1]
tot = counts[0] + counts[1]
prop0 = counts[0] / tot
prop1 = counts[1] / tot
prop0, prop1

(0.07008413982858847, 0.9299158601714116)

In [27]:
forest_clf = RandomForestClassifier(random_state=42, class_weight={0: prop0, 1: prop1}, n_jobs=-1)

In [28]:
X_train.shape, y_train.shape

((10564889, 16), (10564889, 1))

In [31]:
forest_clf.fit(X_train, y_train.ravel())

RandomForestClassifier(bootstrap=True,
            class_weight={0: 0.07008413982858847, 1: 0.9299158601714116},
            criterion='gini', max_depth=None, max_features='auto',
            max_leaf_nodes=None, min_impurity_decrease=0.0,
            min_impurity_split=None, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            n_estimators=10, n_jobs=-1, oob_score=False, random_state=42,
            verbose=0, warm_start=False)

In [33]:
from sklearn.model_selection import cross_val_score, cross_val_predict
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

def print_score(clf, X_train, y_train, X_test, y_test, train=True):
    '''
    Print the accuracy score, classification report, and confusion matrix of classifier.
    '''
    if train:
        '''
        Training Performance
        '''
        print("Train Result:\n")
        print("Accuracy Score: {0:.4f}\n".format(accuracy_score(y_train, clf.predict(X_train))))
        print("Classification Report:\n {} \n".format(classification_report(y_train, clf.predict(X_train))))
        print("Confusion Matrix:  \n {} \n".format(confusion_matrix(y_train, clf.predict(X_train))))
        
        res = cross_val_score(clf, X_train, y_train, cv=5, scoring='accuracy', n_jobs=-1)
        print("Average Accuracy: \t {0:.4f}".format(np.mean(res)))
        print("Accuracy SD \t\t {0:.4f}".format(np.std(res)))
        
    elif train==False:
        '''
        Test Performance
        '''
        print("Test Result:\n")
        print("Accuracy Score: {0:.4f}\n".format(accuracy_score(y_test, clf.predict(X_test))))
        print("Classification Report:\n {} \n".format(classification_report(y_test, clf.predict(X_test))))
        print("Confusion Matrix:  \n {} \n".format(confusion_matrix(y_test, clf.predict(X_test))))

In [34]:
print_score(forest_clf, X_train, y_train.ravel(), X_test, y_test.ravel(), train=True)

Train Result:

Accuracy Score: 0.9452

Classification Report:
              precision    recall  f1-score   support

          0       0.98      0.22      0.36    739929
          1       0.94      1.00      0.97   9824960

avg / total       0.95      0.95      0.93  10564889
 

Confusion Matrix:  
 [[ 164386  575543]
 [   3672 9821288]] 

Average Accuracy: 	 0.9251
Accuracy SD 		 0.0000


In [35]:
print_score(forest_clf, X_train, y_train.ravel(), X_test, y_test.ravel(), train=False)

Test Result:

Accuracy Score: 0.9250

Classification Report:
              precision    recall  f1-score   support

          0       0.18      0.02      0.04    185610
          1       0.93      0.99      0.96   2455613

avg / total       0.88      0.92      0.90   2641223
 

Confusion Matrix:  
 [[   3675  181935]
 [  16250 2439363]] 



## XGBoost

NEED TO CONVERT TO DUMMY VARIABLES (BOOL) FOR THIS TO WORK

In [38]:
import xgboost as xgb

In [40]:
xgb_clf = xgb.XGBClassifier(max_depth=5, n_estimators=500, learning_rate=0.2)

In [42]:
xgb_clf.fit(X_train, y_train)

C:\Users\User\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:95: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\User\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:128: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


ValueError: DataFrame.dtypes for data must be int, float or bool.
                Did not expect the data types in fields CODE_1, CODE_2, CODE_3, CODE_4, CODE_5, CODE_6, CODE_7, Asthma, COPD, Diabetes, HeartFailure, Hypertension, Psychoses, MoodDisorder